### ISSUE TITLE
Идея: единый источник для информации об участниках статей

### ISSUE THREAD

**Issue by hudochenkov** [web-standards-ru/nouvelle#115]
Сейчас в каждой статье все участники записаны с их имененем и адресом. Легко сделать опечатку. Или если нужно изменить адрес, то нужно это сделать во всех файлах.

Предлагаю собрать всю информацию об участниках в одном JSON, чтобы был один источник информации о человеке.

Что есть сейчас в `.md`:

```yaml
author:
    name: 'Хейдон Пикеринг'
    url: 'https://www.heydonworks.com/'
translators:
  - name: 'Татьяна Фокина'
    url: 'https://medium.com/@fokinatatiana'
editors:
  - name: 'Вадим Макеев'
    url: 'https://twitter.com/pepelsbey'
```

Что предлагаю:

```yaml
# В markdown

author: heydon-pickering
translators:
  - tatiana-fokina
editors:
  - vadim-makeev
```

```js
// people.json

{
    "heydon-pickering": {
        "name": "Хейдон Пикеринг",
        "url": "https://www.heydonworks.com/"
    },
    "tatiana-fokina": {
        "name": "Татьяна Фокина",
        "url": "https://medium.com/@fokinatatiana"
    },
    "vadim-makeev": {
        "name": "Вадим Макеев",
        "url": "https://twitter.com/pepelsbey"
    }
}

// или

[
    {
        "id": "heydon-pickering",
        "name": "Хейдон Пикеринг",
        "url": "https://www.heydonworks.com/"
    },
    {
        "id": "tatiana-fokina",
        "name": "Татьяна Фокина",
        "url": "https://medium.com/@fokinatatiana"
    },
    {
        "id": "vadim-makeev",
        "name": "Вадим Макеев",
        "url": "https://twitter.com/pepelsbey"
    }
]
```

~~Можно будет настроить Eleventy показывать предупреждение, если человек с ID не добавлен в общий список. Поможет избежать опечаток.~~ Не знаю как это сделать ¯﻿\﻿_﻿(﻿ツ﻿)﻿_﻿/﻿¯

Это решение поможет с https://github.com/web-standards-ru/nouvelle/issues/108. Нужно будет чтобы `id` совпадал с именем файла.

Впоследствие, поможет интегрировать словарь Веб-стандартов https://github.com/web-standards-ru/nouvelle/issues/19.
