### ISSUE TITLE
Указать в мете для переводных статей автора

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#97]
Нужно в мете переводной статьи указать настоящего автора, чтобы не было случаев, что нет автора, но есть переводчик.

Ориентировочно нужно сделать из:
```
source:
    title: 'Why and how to use WebP images today'
    url: 'https://bitsofco.de/why-and-how-to-use-webp-images-today/'
    author: 'Ире Адеринокун'
```

Отдельное поле
```
source:
    title: 'Why and how to use WebP images today'
    url: 'https://bitsofco.de/why-and-how-to-use-webp-images-today/'
authors:
  - name: 'Ире Адеринокун'
    url: 'https://bitsofco.de/'
```
